# Generated by Django 2.2.8 on 2020-01-24 12:38

from django.db import migrations, models
import players.models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20200122_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='image_2',
        ),
        migrations.AddField(
            model_name='message',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=players.models.upload_image, verbose_name='Photo'),
        ),
    ]
