# Generated by Django 2.2.8 on 2020-01-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_auto_20200124_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='User'),
        ),
    ]
